# filter.toml: 过滤中间件配置文件
[FreqControl]
Enable = false
 
# Sign 接口签名校验配置
[Sign]
# 不走签名校验的特殊sign
Sign = "fsdfgasdgf34578348jiren"
# 不走签名校验的特殊接口
NoSignPath = ["/cms"]

# Token 接口token校验配置
[Token]
# Token
Token = "hnF7w%P%+Jh#P2-~DgJ}32.-acX4M}14"
# 不走amis token校验的特殊接口
NoTokenPath = ["/remote"]